apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  name: rhel9-simplevm
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: root
    spec:
      sourceRef:
        kind: DataSource
        name: rhel9
        namespace: openshift-virtualization-os-images
      storage:
        resources:
          requests:
            storage: 30Gi
  instancetype:
    name: u1.medium
  preference:
    inferFromVolume: root
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        resources: {}
        devices:
          disks:
            - disk:
                bus: virtio
              name: root
            - disk:
                bus: virtio
              name: cloudinitdisk        
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: root
        name: root
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: cloud-user
            password: h6ly-51xg-sdc4
            chpasswd: { expire: False }
        name: cloudinitdisk